Add check if required functions and tables for layer are existing
openmaptiles/openmaptiles-tools pull request #370
Opened 2021-09-11 08:43 UTC by Falke-Design

This PR makes it possible to add a check if required tables and functions are existing. 
Issue: https://github.com/openmaptiles/openmaptiles/issues/1220

In the layer.yaml there are two new entries `required_tables` and `required_functions` as child of `datasource`:

```
layer:
  datasource:
    geometry_field: geometry
    query: (SELECT geometry, admin_level, adm0_l, adm0_r, disputed, disputed_name, claimed_by, maritime FROM layer_boundary(!bbox!, z(!scale_denominator!))) AS t
    required_tables: [table1,table2]
    required_function: [fnc1]
```
or
```
layer:
  datasource:
    geometry_field: geometry
    query: (SELECT geometry, admin_level, adm0_l, adm0_r, disputed, disputed_name, claimed_by, maritime FROM layer_boundary(!bbox!, z(!scale_denominator!))) AS t
    required_tables:
      - table1
      - table2
    required_function:
      - fnc1
```

Workflow:
1. It adds two new function `is_table_existing` and `is_function_existing` in the `run_fist.sql`
2. add to the top of each layer.sql the file a check if the tables / functions are existing.

It looks like
```
SELECT is_table_existing('table1');
```

Generated `boundary.sql`:
```

DO $$ BEGIN RAISE NOTICE 'Processing layer boundary'; END$$;

-- Check if required tables are existing:

SELECT is_table_existing('test');

SELECT is_table_existing('hallo');

-- Check if required functions are existing:

SELECT is_function_existing('fnctest');

-- Layer boundary - ./boundary_name.sql

DROP TABLE IF EXISTS osm_border_linestring_adm CASCADE;

....
```

`import-sql` Log:
```
Importing 1 sql files from /sql/parallel/, up to 5 files at the same time
Importing /sql/parallel/boundary.sql (md5 0017a0f3a5df6a16672772d4cfd6ecfa  -  1000 lines) into Postgres...
Timing is on.
psql:/sql/parallel/boundary.sql:1: NOTICE:  Processing layer boundary
DO
Time: 0.876 ms
psql:/sql/parallel/boundary.sql:5: ERROR:  The required table test is NOT existing!
CONTEXT:  PL/pgSQL function is_table_existing(text) line 4 at RAISE
Time: 2.670 ms
xargs: sh: exited with status 255; aborting
make: *** [Makefile:416: import-sql] Error 124
```
```
Importing 1 sql files from /sql/parallel/, up to 5 files at the same time
Importing /sql/parallel/boundary.sql (md5 3eee0e0f1444cda0c249e98b58a7ab6b  -  1000 lines) into Postgres...
Timing is on.
psql:/sql/parallel/boundary.sql:1: NOTICE:  Processing layer boundary
DO
Time: 0.837 ms
psql:/sql/parallel/boundary.sql:11: ERROR:  The required function fnctest is NOT existing!
CONTEXT:  PL/pgSQL function is_function_existing(text) line 4 at RAISE
Time: 2.525 ms
xargs: sh: exited with status 255; aborting
make: *** [Makefile:416: import-sql] Error 124
```

2021-09-11 19:24 UTC, nyurik requested changes
Thanks for working on this!  There are a few things I think need changing, but this is a great start.

* I don't think we should create global functions just to validate something. All SQL here is dynamically generated, so we can write out any validation logic without using functions. For example, `SELECT 'table'::regclass;` would validate that the table exists and raise an error if it does not.  Also, validating functions should include function signature, e.g. `myfunc(TEXT)` See comment with proposed code change.
* we need to validate yaml during the initial parsing
* naming - i'm not sure what we should name these vars. One idea is to call them   `external_tables` -- implying that these tables come from another layer. We already use  `requires` to indicate external **layers**, so having `required_tables` might be confusing? Or not.

2021-09-11 19:24 UTC, nyurik commented on openmaptiles/sql.py
> +    exist_check = ""
I think it is better to just add all this at the top of the function as a "result" var, and keep appending to it. Also, we can use a much simpler `SELECT '<table>'::regclass;`  here instead. 

```
     result = ''
     for table in layer.required_tables:
         result += f"-- Assert {table} exists\nSELECT '{table}'::regclass;\n\n"
     for func in layer.required_functions:
         result += f"-- Assert {func} exists\nSELECT '{func}'::regprocedure;\n\n"
     ...
     result += sql
     return result
```

2021-09-11 19:24 UTC, nyurik commented on openmaptiles/sql.py
> +def create_fnc_is_table_existing():
we probably should not create global functions that are only needed during the import

2021-09-11 23:08 UTC, Falke-Design commented
How should validating while initial parsing work? At this moment no tables / functions are generated, so it can't checked if they are existing. The checks can only be made while calling the sql of the layer and all steps before are done (like create table).

What if we make a breaking change and make the structure like that:
```
required:
  layers: []
  tables: []
  functions: []
```

2021-09-12 00:30 UTC, nyurik commented
By "validate" i meant check that yaml is correct. `Layer.__init__` does all yaml validation. I just realized that all properties are also tested this way using `validate_properties()`.  So lets keep the properties, but maybe just name them a little bit different - there should be no `get` in a property name (properties are like nouns, and functions are like verbs) - `requires_tables`, `requires_functions`.

I'm ok to redefine `requires` to be a dictionary. We can easily make it backwards compatible -- if `requires` is a string, treat it as a list with a single element.  If `requires` is a list, treat it as a dictionary with a list of layers.  See how `__init__` parses `requires`.

2021-09-13 16:04 UTC, nyurik reviewed
Thanks, I added a few more comments.  Overall, I think it will be simpler to create a helper function that tests and normalizes just one property, and call it from the `__init__`:

```
requires = self.definition['layer'].get('requires', {})
if not isinstance(requires, dict):
    requires['layers'] = requires
else:
    requires = requires.copy()  # dict will be modified to detect unrecognized properties

err = "If set, 'requires' parameter must be a map with optional 'layers', 'tables', and 'functions' sub-elements. Each sub-element must be a string or a list of strings. If 'requires' is a list or a string itself, it is treated as a list of layers. "

self.requires_layers = get_requires_prop(requires, 'layers', err + "'requires.layers' must be an ID of another layer, or a list of layer IDs.")
self.requires_tables = get_requires_prop(requires, 'tables', err + "'requires.tables' must be the name of a PostgreSQL table or a view, or a list of tables/views")
self.requires_functions = get_requires_prop(requires, 'functions', err + "'requires.functions' must be a PostgreSQL function name with parameters or a list of functions. Example: 'myfunc(TEXT, TEXT)' ")

if requires:
  # get_requires_prop will delete the key it handled. Remaining keys are errors.
  raise ValueError("Unrecognized sub-elements in the 'requires' parameter:" + +str(list(requires.keys()))
```

2021-09-14 20:09 UTC, Falke-Design commented
I will change it.
Do you now want that the layer.yaml looks like that:
```
requires:
  layers: []
  tables: []
  functions: []
```
or that?:
```
requires: deprecated warning and internal mapping to requires_layers
requires_layers: []
requires_tables: []
requires_functions: []
```

What I not really understand is why there are `@property`s if we don't define all possible properties? Like you says `requires_*` should now checked in `__init__` but then they are not defined as property anymore?

2021-09-14 20:20 UTC, nyurik commented
sorry for confusion - I think it is cleaner to have YAML as a subtree -- makes it more readable and easier to change:

```
requires:
  layers: []
  tables: []
  functions: []
```

but in python, it is better to have dedicated class fields for each one -- fields are easier to work with and more predictable than having a generic dictionary - hence `requires_layers`, ...

There is little difference between a `@property` and a class field from the usage perspective -- both are used with a dot -- `layer.some_property`. I think in this specific case a field is better than a property because you want to validate that `requires` has only known sub-elements, so might as well do it all at once, but you are welcome to do them as properties too.

2021-09-14 21:07 UTC, Falke-Design commented
I updated now the code and the wanted chages. Thanks for the review, it is now much cleaner! 

In my eyes I would change one thing. You suggested to move the requires parsing into the `__init__` I think it would be better to do this in a own function too. Because now we have this code twice, one time for `tileset.py` and the other one in the `test_sql.py`.
With a own function it would be possible to call it from `test_sql.py`.

Also I tried to add tests if it throws Exception with wrong inputs but it was not possible for me.

2021-09-14 21:15 UTC, nyurik commented
why do you need to duplicate code in a test?

2021-09-14 21:28 UTC, Falke-Design commented
In the test_sql.py the function `query` needs the parsed `requires` fields to be added to the `Case`. Currently the only way to parse requires is to copy the `__init__` logic, because there are tests with the old, new, combined `requires` field.

It would be cleaner to get the parsed data from the tileset-layer and add it to the Case but i have not found a way. (Maybe the id can be used to find the correct layer in the tileset. But now I go to bed)

2021-09-15 02:31 UTC, nyurik commented
ok, thx, i see the issue. I think the simplest solution would be to refactor the test file a bit to cover this usecase - I can do it myself tomorrow if its ok with you.  The rest of the code looks good except for one thing -- please add a property `requires`:

```
    @property
    @deprecated(version='5.4.0', reason='use requires_layers property instead')
    def requires(self) -> List[str]:
        return self.requires_layers
```

2021-09-15 21:35 UTC, nyurik commented
I reworked your tests a bit, please let me know if you are ok with the changes, and I can merge things once all tests pass (optionally we might want another person to review)

2021-09-15 21:40 UTC, nyurik approved these changes

2021-09-16 01:55 UTC, nyurik commented
nope, found another bug (fixed) -- `to_sql` gets called for each schema (SQL file) in a layer. We don't want to assert for each schema, we just want to do it once per layer.

2021-09-16 05:15 UTC, Falke-Design commented on tests/python/test_sql.py
> +    def _parse_reqs(self, reqs, expected_layers, expected_tables, expected_funcs):
would be `_parse_props` not better instead `_parse_reqs` because you test here all properties not only requires

2021-09-16 05:17 UTC, Falke-Design commented
@nyurik  Nice work! Thank you for your help

2021-09-16 13:48 UTC, nyurik commented
@Falke-Design thx, updated. Could you update the first comment to describe the current design? I will copy that comment into the squash commit message when ready.

2021-09-16 14:09 UTC, Falke-Design commented
@nyurik Done. Is this ok so? Else can you please change it?

2021-09-17 14:36 UTC, TomPohys commented
Thank you both for working on this! It looks great!

2021-09-17 14:36 UTC, TomPohys approved these changes

2021-09-17 14:37 UTC, merged